server:
  port: 8083

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: parking-lot-client
            client-secret: Yn1LstkIp4Inb2kenvOF8bN7369GZpR8
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/parking-lot
            user-name-attribute: preferred_username

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: ticket-service-route
          uri: http://localhost:8000
          predicates:
            - Path=/api/v1/**
        - id: vite-frontend
          uri: http://localhost:5173
          predicates:
            - Path=/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG